spring:
  application:
    name: multi-tenancy

multitenant:
  - id: 0
    url: jdbc:mysql://localhost:3306/first_corp
    username: root
    password: root

  - id: 1
    url: jdbc:mysql://localhost:3306/second_corp
    username: root
    password: root